### ISSUE TITLE
Elkészült megoldás

### ISSUE THREAD

**Issue by belaarany** [david-szabo97/dv-mini-exercise-project-weight-tracker#1]
Szia!

Van egy elkészült megoldásom, kíváncsi vagyok az észrevételeidre/tippjeidre. :wink: 

https://github.com/belaarany/weight-tracker-exercise

**Comment by david-szabo97** [comment]
Szia! Belelestem, nagyon jónak igérkezik! Hétvégén átvizsgálom alaposabban!
